// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCE-8BygOAdk-UIKxgxANiRB9_mUmT1PGI',
    appId: '1:312868802011:web:cc50b0f6cc09996b17abfe',
    messagingSenderId: '312868802011',
    projectId: 'assignment-17841',
    authDomain: 'assignment-17841.firebaseapp.com',
    storageBucket: 'assignment-17841.firebasestorage.app',
    measurementId: 'G-8Y9VBRTHLM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBHNFtimBPC9RRwTlivHDeXeWuLoQB7NWs',
    appId: '1:312868802011:android:ee1ee920d908e6b917abfe',
    messagingSenderId: '312868802011',
    projectId: 'assignment-17841',
    storageBucket: 'assignment-17841.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDCEzO8FH3HDaocVuiESzJ4w3LRmdkxEGo',
    appId: '1:312868802011:ios:0bc44f5a1803327717abfe',
    messagingSenderId: '312868802011',
    projectId: 'assignment-17841',
    storageBucket: 'assignment-17841.firebasestorage.app',
    iosBundleId: 'com.example.assignment',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDCEzO8FH3HDaocVuiESzJ4w3LRmdkxEGo',
    appId: '1:312868802011:ios:0bc44f5a1803327717abfe',
    messagingSenderId: '312868802011',
    projectId: 'assignment-17841',
    storageBucket: 'assignment-17841.firebasestorage.app',
    iosBundleId: 'com.example.assignment',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCE-8BygOAdk-UIKxgxANiRB9_mUmT1PGI',
    appId: '1:312868802011:web:f3782f0eadb2a90a17abfe',
    messagingSenderId: '312868802011',
    projectId: 'assignment-17841',
    authDomain: 'assignment-17841.firebaseapp.com',
    storageBucket: 'assignment-17841.firebasestorage.app',
    measurementId: 'G-CGSRNNQ24R',
  );
}
